# Generated by Django 4.2.4 on 2023-08-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Walk Date')),
                ('time_start', models.TimeField(verbose_name='Walk Start')),
                ('time_end', models.TimeField(verbose_name='Walk End')),
                ('length', models.IntegerField(verbose_name='Miles')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='dog',
            name='walks',
            field=models.ManyToManyField(to='main_app.walk'),
        ),
    ]
