# Generated by Django 4.2.4 on 2023-08-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_walk_alter_dog_options_dog_walks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='walks',
        ),
        migrations.AddField(
            model_name='walk',
            name='dogs',
            field=models.ManyToManyField(to='main_app.dog'),
        ),
    ]
