# Generated by Django 4.2.4 on 2023-08-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_dog_walks_walk_dogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='dogs',
            field=models.ManyToManyField(related_name='walks', to='main_app.dog'),
        ),
    ]
